/*
 * HdfGui.java
 *
 * Created on 4. Mai 2002, 01:24
 */

package tuxonhumax.tools.jHDF;

import java.lang.Boolean;
/**
 *
 * @author Ben96
 */
public class HdfGui extends javax.swing.JFrame {
    
    /** Creates new form HdfGui */
    public HdfGui() {
        String hdfFileName = "";
        HdfFile hdfFile = null;
        initComponents();
        hdfFileName = "";
        hdfFile = new HdfFile();
    try
    {
      jbInit();
    }
    catch(Exception e)
    {
      e.printStackTrace();
    }

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        dfFileName = new javax.swing.JTextField();
        sOutput = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        MnuOpenHdf = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuClose = new javax.swing.JMenuItem();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("jHDF-Tool");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Hdf-File :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        getContentPane().add(dfFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 300, -1));

        sOutput.setWrapStyleWord(true);
        sOutput.setColumns(80);
        sOutput.setRows(25);
        getContentPane().add(sOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jMenu2.setText("File");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        MnuOpenHdf.setToolTipText("Opens a Dialogbox to chose a HDF-File");
        MnuOpenHdf.setText("Open HDF-File ...");
        MnuOpenHdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuOpenHdfActionPerformed(evt);
            }
        });

        jMenu2.add(MnuOpenHdf);
        jMenu2.add(jSeparator1);
        mnuClose.setToolTipText("Quit the Application");
        mnuClose.setText("Quit");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });

        jMenu2.add(mnuClose);
        jMenuBar2.add(jMenu2);
        setJMenuBar(jMenuBar2);

        pack();
    }//GEN-END:initComponents
    
    private void MnuOpenHdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuOpenHdfActionPerformed
        int isFile = 0;
        isFile=setFileName();
        dfFileName.setText(hdfFileName);
        if (isFile==1) 
        {
          computeHdfInfo();
          printReport();
          String sTemp="";
          sTemp = hdfFile.toString();
          sOutput.setText(sTemp);
        }
    }//GEN-LAST:event_MnuOpenHdfActionPerformed
    
    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuCloseActionPerformed
    
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new HdfGui().show();
    }
    public int setFileName() {
        final javax.swing.JFileChooser fd = new javax.swing.JFileChooser();
        fd.setApproveButtonText("Open HDF-File ...");
        int returnVal = fd.showOpenDialog(null);
        fd.setVisible(true);
        if (returnVal == fd.APPROVE_OPTION)
        {
            hdfFileName = fd.getCurrentDirectory().getPath()+fd.getSelectedFile().getName();
            dfFileName.setText(hdfFileName);
            return 1;
        }
        return 0;
    }
    
    public void computeHdfInfo() {
        hdfFile.setHdfFileName(hdfFileName);
        hdfFile.computeHdfInfo();
    }
    
    
    public void printReport() {
        System.out.print(hdfFile);
    }
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JTextArea sOutput;
    private javax.swing.JMenuItem MnuOpenHdf;
    private javax.swing.JTextField dfFileName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables

    public String hdfFileName;    
    HdfFile hdfFile     = null;

  private void jbInit() throws Exception
  {
    MnuOpenHdf.setText("Open HDF-Datei ...");
  }

}
